@id=2f51ebbd-ba27-47fd-8cf2-c7df180760eb

PUT https://localhost:7032/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Non-Vegan Sunshine",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}